[main]
window_size = [1749, 923]
window_title = "Tidal Conquer: Overhauled"
window_bg_color = [16, 18, 17]
render_size = [1280, 720] # DO NOT CHANGE
fps = 60
debug = False

[audio]
master = 1.0
music = 1.0
